# config/routes.yaml
controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api

generate_pdf:
    path: /generate-pdf
    controller: App\Controller\EventController::generatePdfAction
